spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welcome to the Spring Boot Tutorial
